<?php

/* custom routes generated by CRUD */


Route::group(array('prefix' => 'admin/prodi/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.prodi.'), function () {

Route::get('prodis', ['as'=> 'prodis.index', 'uses' => 'Prodi\ProdiController@index']);
Route::post('prodis', ['as'=> 'prodis.store', 'uses' => 'Prodi\ProdiController@store']);
Route::get('prodis/create', ['as'=> 'prodis.create', 'uses' => 'Prodi\ProdiController@create']);
Route::put('prodis/{prodis}', ['as'=> 'prodis.update', 'uses' => 'Prodi\ProdiController@update']);
Route::patch('prodis/{prodis}', ['as'=> 'prodis.update', 'uses' => 'Prodi\ProdiController@update']);
Route::get('prodis/{id}/delete', array('as' => 'prodis.delete', 'uses' => 'Prodi\ProdiController@getDelete'));
Route::get('prodis/{id}/confirm-delete', array('as' => 'prodis.confirm-delete', 'uses' => 'Prodi\ProdiController@getModalDelete'));
Route::get('prodis/{prodis}', ['as'=> 'prodis.show', 'uses' => 'Prodi\ProdiController@show']);
Route::get('prodis/{prodis}/edit', ['as'=> 'prodis.edit', 'uses' => 'Prodi\ProdiController@edit']);

});





Route::group(array('prefix' => 'admin/dosen/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.dosen.'), function () {

    Route::get('dosens', ['as'=> 'dosens.index', 'uses' => 'Dosen\DosenController@index']);
    Route::post('dosens', ['as'=> 'dosens.store', 'uses' => 'Dosen\DosenController@store']);
    Route::get('dosens/create', ['as'=> 'dosens.create', 'uses' => 'Dosen\DosenController@create']);
    Route::put('dosens/{dosens}', ['as'=> 'dosens.update', 'uses' => 'Dosen\DosenController@update']);
    Route::patch('dosens/{dosens}', ['as'=> 'dosens.update', 'uses' => 'Dosen\DosenController@update']);
    Route::get('dosens/{id}/delete', array('as' => 'dosens.delete', 'uses' => 'Dosen\DosenController@getDelete'));
    Route::get('dosens/{id}/confirm-delete', array('as' => 'dosens.confirm-delete', 'uses' => 'Dosen\DosenController@getModalDelete'));
    Route::get('dosens/{dosens}', ['as'=> 'dosens.show', 'uses' => 'Dosen\DosenController@show']);
    Route::get('dosens/{dosens}/edit', ['as'=> 'dosens.edit', 'uses' => 'Dosen\DosenController@edit']);

    });


Route::group(array('prefix' => 'admin/fokus/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.fokus.'), function () {

Route::get('foci', ['as'=> 'foci.index', 'uses' => 'Fokus\FocusController@index']);
Route::post('foci', ['as'=> 'foci.store', 'uses' => 'Fokus\FocusController@store']);
Route::get('foci/create', ['as'=> 'foci.create', 'uses' => 'Fokus\FocusController@create']);
Route::put('foci/{foci}', ['as'=> 'foci.update', 'uses' => 'Fokus\FocusController@update']);
Route::patch('foci/{foci}', ['as'=> 'foci.update', 'uses' => 'Fokus\FocusController@update']);
Route::get('foci/{id}/delete', array('as' => 'foci.delete', 'uses' => 'Fokus\FocusController@getDelete'));
Route::get('foci/{id}/confirm-delete', array('as' => 'foci.confirm-delete', 'uses' => 'Fokus\FocusController@getModalDelete'));
Route::get('foci/{foci}', ['as'=> 'foci.show', 'uses' => 'Fokus\FocusController@show']);
Route::get('foci/{foci}/edit', ['as'=> 'foci.edit', 'uses' => 'Fokus\FocusController@edit']);

});


Route::group(array('prefix' => 'admin/headerCarousel/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.headerCarousel.'), function () {

Route::get('headerCarousels', ['as'=> 'headerCarousels.index', 'uses' => 'Headercarousel\HeaderCarouselController@index']);
Route::post('headerCarousels', ['as'=> 'headerCarousels.store', 'uses' => 'Headercarousel\HeaderCarouselController@store']);
Route::get('headerCarousels/create', ['as'=> 'headerCarousels.create', 'uses' => 'Headercarousel\HeaderCarouselController@create']);
Route::put('headerCarousels/{headerCarousels}', ['as'=> 'headerCarousels.update', 'uses' => 'Headercarousel\HeaderCarouselController@update']);
Route::patch('headerCarousels/{headerCarousels}', ['as'=> 'headerCarousels.update', 'uses' => 'Headercarousel\HeaderCarouselController@update']);
Route::get('headerCarousels/{id}/delete', array('as' => 'headerCarousels.delete', 'uses' => 'Headercarousel\HeaderCarouselController@getDelete'));
Route::get('headerCarousels/{id}/confirm-delete', array('as' => 'headerCarousels.confirm-delete', 'uses' => 'Headercarousel\HeaderCarouselController@getModalDelete'));
Route::get('headerCarousels/{headerCarousels}', ['as'=> 'headerCarousels.show', 'uses' => 'Headercarousel\HeaderCarouselController@show']);
Route::get('headerCarousels/{headerCarousels}/edit', ['as'=> 'headerCarousels.edit', 'uses' => 'Headercarousel\HeaderCarouselController@edit']);

});

Route::group(array('prefix' => 'admin/gallery/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.gallery.'), function () {

Route::get('galleryPhotos', ['as'=> 'galleryPhotos.index', 'uses' => 'Gallery\GalleryPhotoController@index']);
Route::post('galleryPhotos', ['as'=> 'galleryPhotos.store', 'uses' => 'Gallery\GalleryPhotoController@store']);
Route::get('galleryPhotos/create', ['as'=> 'galleryPhotos.create', 'uses' => 'Gallery\GalleryPhotoController@create']);
Route::put('galleryPhotos/{galleryPhotos}', ['as'=> 'galleryPhotos.update', 'uses' => 'Gallery\GalleryPhotoController@update']);
Route::patch('galleryPhotos/{galleryPhotos}', ['as'=> 'galleryPhotos.update', 'uses' => 'Gallery\GalleryPhotoController@update']);
Route::get('galleryPhotos/{id}/delete', array('as' => 'galleryPhotos.delete', 'uses' => 'Gallery\GalleryPhotoController@getDelete'));
Route::get('galleryPhotos/{id}/confirm-delete', array('as' => 'galleryPhotos.confirm-delete', 'uses' => 'Gallery\GalleryPhotoController@getModalDelete'));
Route::get('galleryPhotos/{galleryPhotos}', ['as'=> 'galleryPhotos.show', 'uses' => 'Gallery\GalleryPhotoController@show']);
Route::get('galleryPhotos/{galleryPhotos}/edit', ['as'=> 'galleryPhotos.edit', 'uses' => 'Gallery\GalleryPhotoController@edit']);

});


Route::group(array('prefix' => 'admin/testimonial/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.testimonial.'), function () {

Route::get('testimonials', ['as'=> 'testimonials.index', 'uses' => 'Testimonial\TestimonialController@index']);
Route::post('testimonials', ['as'=> 'testimonials.store', 'uses' => 'Testimonial\TestimonialController@store']);
Route::get('testimonials/create', ['as'=> 'testimonials.create', 'uses' => 'Testimonial\TestimonialController@create']);
Route::put('testimonials/{testimonials}', ['as'=> 'testimonials.update', 'uses' => 'Testimonial\TestimonialController@update']);
Route::patch('testimonials/{testimonials}', ['as'=> 'testimonials.update', 'uses' => 'Testimonial\TestimonialController@update']);
Route::get('testimonials/{id}/delete', array('as' => 'testimonials.delete', 'uses' => 'Testimonial\TestimonialController@getDelete'));
Route::get('testimonials/{id}/confirm-delete', array('as' => 'testimonials.confirm-delete', 'uses' => 'Testimonial\TestimonialController@getModalDelete'));
Route::get('testimonials/{testimonials}', ['as'=> 'testimonials.show', 'uses' => 'Testimonial\TestimonialController@show']);
Route::get('testimonials/{testimonials}/edit', ['as'=> 'testimonials.edit', 'uses' => 'Testimonial\TestimonialController@edit']);

});


Route::group(array('prefix' => 'admin/tugasAkhir/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.tugasAkhir.'), function () {

Route::get('tugasAkhirs', ['as'=> 'tugasAkhirs.index', 'uses' => 'Tugasakhir\TugasAkhirController@index']);
Route::post('tugasAkhirs', ['as'=> 'tugasAkhirs.store', 'uses' => 'Tugasakhir\TugasAkhirController@store']);
Route::get('tugasAkhirs/create', ['as'=> 'tugasAkhirs.create', 'uses' => 'Tugasakhir\TugasAkhirController@create']);
Route::put('tugasAkhirs/{tugasAkhirs}', ['as'=> 'tugasAkhirs.update', 'uses' => 'Tugasakhir\TugasAkhirController@update']);
Route::patch('tugasAkhirs/{tugasAkhirs}', ['as'=> 'tugasAkhirs.update', 'uses' => 'Tugasakhir\TugasAkhirController@update']);
Route::get('tugasAkhirs/{id}/delete', array('as' => 'tugasAkhirs.delete', 'uses' => 'Tugasakhir\TugasAkhirController@getDelete'));
Route::get('tugasAkhirs/{id}/confirm-delete', array('as' => 'tugasAkhirs.confirm-delete', 'uses' => 'Tugasakhir\TugasAkhirController@getModalDelete'));
Route::get('tugasAkhirs/{tugasAkhirs}', ['as'=> 'tugasAkhirs.show', 'uses' => 'Tugasakhir\TugasAkhirController@show']);
Route::get('tugasAkhirs/{tugasAkhirs}/edit', ['as'=> 'tugasAkhirs.edit', 'uses' => 'Tugasakhir\TugasAkhirController@edit']);

});
